### ISSUE TITLE
[Discuss] 使用 Scrcpy 替代截图的可行性

### ISSUE THREAD

**Issue by MC-ALL** [pur1fying/blue_archive_auto_script#49]
## 参见
[Scrcpy 的Github仓库](https://github.com/Genymobile/scrcpy)

## 优点
1. Scrcpy-Server 直接在模拟器运行，屏幕捕获并封装成tcp视频流，参见[官方文档](https://github.com/Genymobile/scrcpy/blob/master/doc/develop.md)，可以在 OpenCV 中使用，提高及时性和准确性。

## 缺点
1. 可能与目前的代码冲突，增加工作量
2. 增加OpenCV的占用

**Comment by pur1fying** [comment]
没有用过，但可以考虑，延迟高吗？

**Comment by MC-ALL** [comment]
> 没有用过，但可以考虑，延迟高吗？

 1. 我只测试过实机，不高，应该低于100ms？再准确的没测。
 2. **潜在的兼容性问题**。刚刚在蓝叠国际版上测试，crash了，看到issues提到这个问题，作者猜测是ROM的原因。手上没有其它模拟器，不排除是个例。

**Comment by Kiramei** [comment]
这个框架的优化空间有多少

**Comment by RedDeadDepresso** [comment]
@pur1fying AAS has scrcpy if that helps. You can use it as a guide when implementing in baas.

https://github.com/TheFunny/ArisuAutoSweeper/tree/master/module/device/method/scrcpy

**Comment by pur1fying** [comment]
@RedDeadDepresso ok

**Comment by XcantloadX** [comment]
Scrcpy 3.0 发布了，新增了“虚拟显示器”功能，可以①**自定义分辨率**，②**同时运行多个应用**，互不干扰。

在物理机上的测试结果：
（右侧为手机实际显示画面，左侧为两个虚拟显示器）
![image](https://github.com/user-attachments/assets/add623a8-a6e7-4e44-a086-700867ff8302)

这个特性很 nb，但是相对模拟器来说貌似没什么显著优势。

**Comment by Kiramei** [comment]
会很卡吗

**Comment by Kiramei** [comment]
@XcantloadX 你有linux上模拟器的方案吗，我看你用的scrcpy能够跑，一般都是用模拟器的，你这个很特别，我在想linux是不是也能用。上次用个redroid进不了游戏会闪退。

**Comment by MC-ALL** [comment]
> @XcantloadX 你有linux上模拟器的方案吗，我看你用的scrcpy能够跑，一般都是用模拟器的，你这个很特别，我在想linux是不是也能用。上次用个redroid进不了游戏会闪退。

可以參考以下連結
[通过对 libhoudini 进行补丁实现在 Waydroid 上运行碧蓝档案国际服](https://www.rayalto.org/2024/08/10/blue-archive-on-waydroid-is-now-working/)

**Comment by MC-ALL** [comment]
> Scrcpy 3.0 发布了，新增了“虚拟显示器”功能，可以①**自定义分辨率**，②**同时运行多个应用**，互不干扰。
> 
> 在物理机上的测试结果： （右侧为手机实际显示画面，左侧为两个虚拟显示器） ![image](https://private-user-images.githubusercontent.com/25605245/390271297-add623a8-a6e7-4e44-a086-700867ff8302.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzY3MzYsIm5iZiI6MTczMjc3NjQzNiwicGF0aCI6Ii8yNTYwNTI0NS8zOTAyNzEyOTctYWRkNjIzYTgtYTZlNy00ZTQ0LWEwODYtNzAwODY3ZmY4MzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA2NDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ODJlNWU5OThlODc5ZGVjMzhkMzdjYjM5MTJlMmQ0N2VmYzBjMzQxM2VhNDY0ZjNhYjZjMGU5M2JhNGE1NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sNJtoNdHFRSRngHVSxSl_iGMOL_MeDoMF_kT96IoyQE)
> 
> 这个特性很 nb，但是相对模拟器来说貌似没什么显著优势。

@XcantloadX  在一個模擬器裏面同時跑兩個app可能比較省主機資源？

**Comment by Kiramei** [comment]
> > @XcantloadX 你有linux上模拟器的方案吗，我看你用的scrcpy能够跑，一般都是用模拟器的，你这个很特别，我在想linux是不是也能用。上次用个redroid进不了游戏会闪退。
> 
> 
> 
> @Kiramei  模擬器可以參考以下連結
> 
> [通过对 libhoudini 进行补丁实现在 Waydroid 上运行碧蓝档案国际服](https://www.rayalto.org/2024/08/10/blue-archive-on-waydroid-is-now-working/)

waydroid对Nvidia兼容性问题怎么解决

**Comment by pur1fying** [comment]
已适配scrcpy截图和控制方式，可以在设置中修改
96df6b73a4ee8dd35016a69827bba3b517591f14
大部分功能已测试，可能有部分功能会有识别问题（原因是scrcpy是有损截图）

**Comment by MC-ALL** [comment]
> 已适配scrcpy截图和控制方式，可以在设置中修改 [96df6b7](https://github.com/pur1fying/blue_archive_auto_script/commit/96df6b73a4ee8dd35016a69827bba3b517591f14) 大部分功能已测试，可能有部分功能会有识别问题（原因是scrcpy是有损截图）

參考了 [py-scrcpy-client](https://github.com/leng-yue/py-scrcpy-client)？是否應該在相關代碼開頭添加回許可證？

**Comment by pur1fying** [comment]
> > 已适配scrcpy截图和控制方式，可以在设置中修改 [96df6b7](https://github.com/pur1fying/blue_archive_auto_script/commit/96df6b73a4ee8dd35016a69827bba3b517591f14) 大部分功能已测试，可能有部分功能会有识别问题（原因是scrcpy是有损截图）
> 
> 參考了 [py-scrcpy-client](https://github.com/leng-yue/py-scrcpy-client)？是否應該在相關代碼開頭添加回許可證？

7d8ed30f5a6f0a5fe005acb29c25656dc96b31a8

**Comment by Kiramei** [comment]
我目前用REDROID的方案，之前还能够使用，不知道从什么时候开始就是不能用，现在一直卡在这：

```
scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 330.2 MB/s (41650 bytes in 0.000s)
Aborted (core dumped) 
ERROR: Server connection failed
```

**Comment by Kiramei** [comment]
目前我切换到AVD，模拟器可以启动，蔚蓝档案闪退。

**Comment by MC-ALL** [comment]
@Kiramei 經測試，`Redroid`可在我的laptop上運行，詳見附圖二之一。國服可以正確啓動且畫面未見異常，唯獨一加載動畫疊加於菜單之上，詳見附圖二之二，可能是賬户功能不正常或者是我網絡問題。

附圖二之一
系統：ArchLinux ，內核：6.12.1，映像檔：`redroid/redroid:12.0.0-latest ` 

![屏幕截图_20241201_162228](https://github.com/user-attachments/assets/cffb9e1b-1c82-4fdf-b5b5-154497f1e325)

附圖二之二
使用 Scrcpy 3.0

![屏幕截图_20241201_163844](https://github.com/user-attachments/assets/ee50062f-7a76-40b1-8dd5-f386c21ceba5)

**Comment by Kiramei** [comment]
> @Kiramei 經測試，`Redroid`可在我的laptop上運行，詳見附圖二之一。國服可以正確啓動且畫面未見異常，唯獨一加載動畫疊加於菜單之上，詳見附圖二之二，可能是賬户功能不正常或者是我網絡問題。
> 
> 
> 
> 附圖二之一
> 
> 系統：ArchLinux ，內核：6.12.1，映像檔：`redroid/redroid:12.0.0-latest ` 
> 
> 
> 
> ![屏幕截图_20241201_162228](https://github.com/user-attachments/assets/cffb9e1b-1c82-4fdf-b5b5-154497f1e325)
> 
> 
> 
> 附圖二之二
> 
> 使用 Scrcpy 3.0
> 
> 
> 
> ![屏幕截图_20241201_163844](https://github.com/user-attachments/assets/ee50062f-7a76-40b1-8dd5-f386c21ceba5)
> 
> 
@MC-ALL 能否给我一个redroid的启动脚本，或者docker-compise的yaml文件。我想复现一下。

**Comment by MC-ALL** [comment]
@Kiramei 我使用的 `docker-compose.yml` 如下所示，大部分來自 [ReDroid教學：用Docker跑Android系統，在x86電腦玩ARM手機遊戲](https://ivonblog.com/posts/redroid-android-docker/)，3D 硬體加速 **不可** 用於 Nvidia 顯示卡，Nvidia 使用者可用 QEMU + virtio-gpu 實現。

```
services:
  redroid:
    image: redroid/redroid:12.0.0-latest 
    stdin_open: true
    tty: true
    privileged: true
    ports:
      - 127.0.0.1:5555:5555 # ADB通訊埠，為加強安全性，設定為只監聽本機localhost的通訊埠
    volumes:
      - ./redroid-12-data:/data # 資料存放在目前目錄下
    command:
      - androidboot.redroid_width=720 # 手機解析度
      - androidboot.redroid_height=1280
      - androidboot.redroid_dpi=320
      - androidboot.redroid_fps=60
      - androidboot.redroid_gpu_mode=host # 啟用宿主機的GPU硬體加速，host為啟用GPU加速，guest為軟體渲染
      - ro.product.cpu.abilist0=x86_64,arm64-v8a,x86,armeabi-v7a,armeabi # 設定libndk相關
      - ro.product.cpu.abilist64=x86_64,arm64-v8a
      - ro.product.cpu.abilist32=x86,armeabi-v7a,armeabi
      - ro.dalvik.vm.isa.arm=x86
      - ro.dalvik.vm.isa.arm64=x86_64
      - ro.enable.native.bridge.exec=1
      - ro.dalvik.vm.native.bridge=libndk_translation.so
      - ro.ndk_translation.version=0.2.3

```
